# Generated by Django 4.2.28 on 2026-04-23 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_separate_role_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='api.company'),
        ),
        migrations.AddField(
            model_name='plate',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='plate_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='plate',
            unique_together={('company', 'plate_number')},
        ),
    ]
